services:
  postgres:
    image: postgres:latest
    container_name: db-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: tradebuddy
    expose:
      - 5432
    volumes:
      - db-data:/var/lib/postgresql/data
    restart: always
    networks:
      - tradebuddy_network

  backend:
    container_name: backend-container
    image: developerjay19/tbb-backend:latest
    build:
      context: ./tbb-backend
      dockerfile: backend.Dockerfile
    environment:
      - API_BASE_URL=http://localhost
    expose:
      - 8000
    depends_on:
      - postgres
    volumes:
      - ./tbb-backend:/backend-app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000","--reload"]
    networks:
      - tradebuddy_network

  nginx:
    image: nginx:latest
    container_name: nginx-container
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf  # Nginx configuration
      - ./nginx/selfsigned.crt:/etc/nginx/ssl/selfsigned.crt  # SSL certificate
      - ./nginx/selfsigned.key:/etc/nginx/ssl/selfsigned.key  # SSL key
    depends_on:
      - backend
    networks:
      - tradebuddy_network
volumes:
  db-data:

networks:
  tradebuddy_network:
    external: true
